package audiotest

import (
	"fmt"
	"math"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestBedTooQuiet(t *testing.T) {
	const n = 48000
	noiseAt := func(db float64) []float32 {
		x := whiteNoise(n, 1, 7)
		ScaleToRMS(x, DBToLin(db))
		return x
	}
	tests := []struct {
		name      string
		bed       []float32
		wantQuiet bool
		wantDB    float64 // expected level; only checked when tol > 0
		tol       float64
	}{
		{"all zeros", make([]float32, n), true, -200, 0.001},
		{"empty", nil, true, -200, 0.001},
		{"noise at -90 dBFS", noiseAt(-90), true, -90, 0.2},
		{"noise just below the limit", noiseAt(-80.1), true, -80.1, 0.2},
		{"noise just above the limit", noiseAt(-79.9), false, -79.9, 0.2},
		{"noise at -70 dBFS", noiseAt(-70), false, -70, 0.2},
		{"recorded-bed level", noiseAt(-54), false, -54, 0.2},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			level, quiet := bedTooQuiet(tt.bed)
			if quiet != tt.wantQuiet {
				t.Errorf("bedTooQuiet = %v at %.2f dBFS, want %v", quiet, level, tt.wantQuiet)
			}
			if math.Abs(level-tt.wantDB) > tt.tol {
				t.Errorf("level = %.3f dBFS, want %.3f (+/- %.3f)", level, tt.wantDB, tt.tol)
			}
		})
	}
}

// genWav writes a mono 48 kHz float32 wav of the given lavfi source to path.
func genWav(t *testing.T, bin, path, source string, seconds int) {
	t.Helper()
	cmd := exec.CommandContext(t.Context(), bin, "-hide_banner", "-nostats", "-v", "error", "-y",
		"-f", "lavfi", "-i", source+fmt.Sprintf(":r=48000:d=%d", seconds),
		"-ac", "1", "-c:a", "pcm_f32le", path)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("ffmpeg %s: %v\n%s", source, err, out)
	}
}

// TestLoadNoiseBed decodes real wav files generated by ffmpeg, so the decode,
// slice and level checks run end to end, not only the predicate.
func TestLoadNoiseBed(t *testing.T) {
	bin := FFmpegPath(t)
	dir := t.TempDir()
	tests := []struct {
		name     string
		source   string
		seconds  int
		wantSkip string // substring of the skip reason; empty means usable
	}{
		{"digital silence", "anullsrc=cl=mono", 12, "below"},
		{"noise at about -95 dBFS", "anoisesrc=c=white:a=0.00003", 12, "below"},
		{"noise at about -55 dBFS", "anoisesrc=c=white:a=0.003", 12, ""},
		{"short but loud", "anoisesrc=c=white:a=0.1", 5, "shorter"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(dir, strings.ReplaceAll(tt.name, " ", "_")+".wav")
			genWav(t, bin, path, tt.source, tt.seconds)
			bed, skip := loadNoiseBed(t, bin, path, corpusSampleRate)
			if tt.wantSkip == "" {
				if skip != "" || len(bed) != synthSeconds*corpusSampleRate {
					t.Fatalf("got skip %q, %d samples; want a full-length usable bed", skip, len(bed))
				}
				return
			}
			if bed != nil || !strings.Contains(skip, tt.wantSkip) {
				t.Fatalf("got %d samples, skip %q; want no bed and a reason containing %q", len(bed), skip, tt.wantSkip)
			}
		})
	}
}
